---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc-001
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: instorage-csi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc-002
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 3Gi
  storageClassName: instorage-csi
