apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshot
metadata:
  name: new-snapshot-demo
spec:
  snapshotClassName: snapshot-csi
  source:
    name: csi-pvc-001
    kind: PersistentVolumeClaim
